In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[
      "the glass of the milk",
      "the glass of the juice",
      "the glass of the water",
      "I am a good boy",
      "I am a good developer",
      "your videos is good",
      "understand the meaning of word"
]

In [3]:
sent

['the glass of the milk',
 'the glass of the juice',
 'the glass of the water',
 'I am a good boy',
 'I am a good developer',
 'your videos is good',
 'understand the meaning of word']

In [4]:
#Vocabullary size
voc_size= 10000

**One hot representation**

In [5]:
onehot_rpr=[one_hot(words, voc_size) for words in sent]
print(onehot_rpr)

[[1480, 9267, 74, 1480, 9742], [1480, 9267, 74, 1480, 894], [1480, 9267, 74, 1480, 7222], [5053, 3209, 779, 3436, 5770], [5053, 3209, 779, 3436, 6819], [9337, 3426, 7671, 3436], [9623, 1480, 4710, 74, 7746]]


**Word embedding representation**

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [9]:
sent_length= 8
emdebed_docs= pad_sequences(onehot_rpr, padding='pre', maxlen= sent_length)
print(emdebed_docs)

[[   0    0    0 1480 9267   74 1480 9742]
 [   0    0    0 1480 9267   74 1480  894]
 [   0    0    0 1480 9267   74 1480 7222]
 [   0    0    0 5053 3209  779 3436 5770]
 [   0    0    0 5053 3209  779 3436 6819]
 [   0    0    0    0 9337 3426 7671 3436]
 [   0    0    0 9623 1480 4710   74 7746]]


In [14]:
model= Sequential()
dimension= 10
model.add(Embedding(voc_size, dimension, input_length= sent_length))
model.compile('adam', 'mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(emdebed_docs))

[[[-0.03953792 -0.04940819 -0.02947687  0.00265555  0.03545464
   -0.03103206  0.01597473 -0.04493228  0.04902654 -0.03740358]
  [-0.03953792 -0.04940819 -0.02947687  0.00265555  0.03545464
   -0.03103206  0.01597473 -0.04493228  0.04902654 -0.03740358]
  [-0.03953792 -0.04940819 -0.02947687  0.00265555  0.03545464
   -0.03103206  0.01597473 -0.04493228  0.04902654 -0.03740358]
  [ 0.03945183 -0.00390657 -0.02353904  0.03325206  0.00141551
   -0.00279929  0.00099856 -0.01687545  0.03627136 -0.00870603]
  [ 0.01283455  0.04316435 -0.03040327  0.03926763  0.0461254
    0.01358882 -0.01073254  0.04641659  0.0382144   0.01939864]
  [-0.04940794 -0.04806015 -0.01096838  0.0322003  -0.03622619
    0.04914222  0.02843365 -0.03544128  0.00447444  0.01217693]
  [ 0.03945183 -0.00390657 -0.02353904  0.03325206  0.00141551
   -0.00279929  0.00099856 -0.01687545  0.03627136 -0.00870603]
  [ 0.01805427 -0.03000424  0.00560611 -0.03163395  0.00699506
    0.0127739   0.04283271 -0.02416486  0.0067784

In [16]:
print(model.predict(emdebed_docs)[0])

[[ 0.01962045  0.02709239  0.02771555  0.00486503 -0.0274558   0.02751115
  -0.03611714 -0.00815595  0.00855815 -0.04210131]
 [ 0.01962045  0.02709239  0.02771555  0.00486503 -0.0274558   0.02751115
  -0.03611714 -0.00815595  0.00855815 -0.04210131]
 [ 0.01962045  0.02709239  0.02771555  0.00486503 -0.0274558   0.02751115
  -0.03611714 -0.00815595  0.00855815 -0.04210131]
 [-0.04302774  0.034768    0.00845272  0.01873097  0.03316421 -0.03674617
   0.02555359 -0.00352776  0.04132134  0.04447429]
 [-0.01118102  0.04696885 -0.04624889 -0.04914271 -0.01550071 -0.02366136
  -0.00686928 -0.01641726 -0.02654697  0.04059303]
 [-0.00139377  0.00386099 -0.04901117  0.00700263  0.02711878  0.04193527
  -0.01244868 -0.02867905  0.01042413  0.01749298]
 [-0.04302774  0.034768    0.00845272  0.01873097  0.03316421 -0.03674617
   0.02555359 -0.00352776  0.04132134  0.04447429]
 [-0.00768789 -0.00484867  0.04830528 -0.03939056 -0.02115315  0.04502677
  -0.03796835 -0.02707067 -0.04157388  0.02333574]]